Imports PackageIO
Imports System.IO
Imports System.Net
Imports System
Public Class TLSE_crcxmodem
    Private IsFormBeingDragged As Boolean = False
    Private MousedwnX As Integer
    Private MousedwnY As Integer
    Dim applicationpath = Application.StartupPath
    Dim AudioTomodachi As System.IO.UnmanagedMemoryStream
    Dim savedataArc As String
    Dim crcxmodem As String
    Private Sub Closebutton_Click(sender As Object, e As EventArgs) Handles Closebutton.Click
        Me.Close()
    End Sub

    Private Sub Closebutton_MouseMove(sender As Object, e As EventArgs) Handles Closebutton.MouseMove
        Closebutton.Image = My.Resources.close_red_tl
    End Sub

    Private Sub Closebutton_MouseLeave(sender As Object, e As EventArgs) Handles Closebutton.MouseLeave
        Closebutton.Image = My.Resources.close_tl
    End Sub

    Private Sub TLSE_header_MouseDown(sender As Object, e As System.Windows.Forms.MouseEventArgs) Handles TLSE_header.MouseDown, TLSE_title.MouseDown
        If e.Button = Windows.Forms.MouseButtons.Left Then
            IsFormBeingDragged = True
            MousedwnX = e.X
            MousedwnY = e.Y
        End If
    End Sub

    Private Sub TLSE_header_MouseUp(sender As Object, e As System.Windows.Forms.MouseEventArgs) Handles TLSE_header.MouseUp, TLSE_title.MouseUp
        If e.Button = Windows.Forms.MouseButtons.Left Then
            IsFormBeingDragged = False
        End If
    End Sub

    Private Sub TLSE_header_MouseMove(sender As Object, e As System.Windows.Forms.MouseEventArgs) Handles TLSE_header.MouseMove, TLSE_title.MouseMove
        If IsFormBeingDragged = True Then
            Dim tmp As Point = New Point()
            tmp.X = Me.Location.X + (e.X - MousedwnX)
            tmp.Y = Me.Location.Y + (e.Y - MousedwnY)
            Me.Location = tmp
            tmp = Nothing
        End If
    End Sub

    Private Sub Minimizebutton_Click(sender As Object, e As EventArgs) Handles Minimizebutton.Click
        Me.WindowState = FormWindowState.Minimized
    End Sub

    Private Sub Minimizebutton_MouseMove(sender As Object, e As MouseEventArgs) Handles Minimizebutton.MouseMove
        Minimizebutton.Image = My.Resources.minimize_gray
    End Sub

    Private Sub Minimizebutton_MouseLeave(sender As Object, e As EventArgs) Handles Minimizebutton.MouseLeave
        Minimizebutton.Image = My.Resources.minimize
    End Sub

    'form menu

    Private Sub TLSE_crcxmodem_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Try
            Setting_Advhelp.Checked = My.Settings.Para_AdvH
            Setting_ckupdate.Checked = My.Settings.Para_chkupdate
            Setting_hidden.Checked = My.Settings.Para_hidden
            Setting_music.Checked = My.Settings.Para_music
            Setting_filepath.Checked = My.Settings.Para_path
            Setting_spesymb.Checked = My.Settings.Para_spesymb
            Select_language.SelectedItem = My.Settings.Para_language
            Select_music.SelectedItem = My.Settings.Para_selmusic
        Catch ex As Exception
        End Try
        TLSE_filepath.Text = TLSE_miiprofile.TLSE_filepath.Text
        Filever_text.Text = TLSE_miiprofile.Filever_text.Text
        savedataArc = TLSE_filepath.Text
        Switchfilever()
        Text_crcmii.Text = "Failed to autofix checksum : Select" & vbNewLine & TLSE_miiprofile.Select_mii.Text
        Readmiiname()
        Select_mii.SelectedItem = TLSE_miiprofile.Select_mii.SelectedItem
    End Sub

    Public Sub Switchfilever()
        If Filever_text.Text = "EU" Then
            TLSE_logo.Image = My.Resources.logo_EU
            TLSE_logo_update.Image = My.Resources.logo_EU_update
        End If
        If Filever_text.Text = "US" Then
            TLSE_logo.Image = My.Resources.logo_US
            TLSE_logo_update.Image = My.Resources.logo_US_update
        End If
        If Filever_text.Text = "JP" Then
            TLSE_logo.Image = My.Resources.logo_JP
            TLSE_logo_update.Image = My.Resources.logo_JP_update
        End If
        If Filever_text.Text = "KR" Then
            TLSE_logo.Image = My.Resources.logo_KR
            TLSE_logo_update.Image = My.Resources.logo_KR_update
        End If
        TLSE_loading_logo.Image = TLSE_logo.Image
    End Sub
    Private Sub Select_mii_SelectedIndexChanged(sender As Object, e As EventArgs) Handles Select_mii.SelectedIndexChanged
        readmiidata()
        XmodemMii()
    End Sub

    Public Sub XmodemMii()
        Dim crc As Integer = &H0 ' Starting value 
        Dim Polynom As Integer = &H1021 ' As in X^16 + X^12 + X^5 + 1 
        Dim bit As Boolean
        Dim c15 As Boolean
        Dim i As Integer
        Dim str As String = Text_Mii.Text
        Dim ctr = PackageIO.Conversions.HexToByteArray(str)
        Dim bytes As Byte() = ctr

        ' Calculate the CRC: 
        For Each b As Byte In bytes
            For i = 0 To 7
                bit = ((b >> (7 - i) And 1)) '= 1) 
                c15 = ((crc >> 15 And 1)) '= 1) 
                crc <<= 1
                If c15 Xor bit Then
                    crc = crc Xor Polynom
                End If
            Next
        Next

        crc = crc And &HFFFF

        Text_crcxmodem.Text = Hex(crc).PadLeft(4, "0")
        Try
            Dim Writecrc As New FileStream(savedataArc, FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite)
            Writecrc.Position = crcxmodem
            For j As Integer = 0 To Text_crcxmodem.Text.Length - 1 Step 2
                Writecrc.WriteByte(CByte(Conversion.Val("&H" & Text_crcxmodem.Text.Substring(j, 2))))
            Next
            TLSE_dialog.Text_TLSE_dialog.Text = "Checksum has been updated, you will back to menu"
            TLSE_dialog.ShowDialog()
            If TLSE_logo_update.Visible = True Then
                TLSE_hub.TLSE_logo_update.Visible = True
            End If
            TLSE_hub.Show()
            TLSE_hub.Filever_text.Text = Filever_text.Text
            TLSE_hub.TLSE_filepath.Text = TLSE_filepath.Text
            TLSE_hub.TLSE_menu.Visible = False
            TLSE_hub.TLSE_menu_Miiedition.Visible = True
            Me.Close()
        Catch ex As Exception
            If Select_language.SelectedItem = Select_language.Items.Item(0) Then
                TLSE_dialog.Text_TLSE_dialog.Text = "Failed to fix checksum, please report this issue"
                TLSE_dialog.ShowDialog()
            End If
            If Select_language.SelectedItem = Select_language.Items.Item(1) Then
                TLSE_dialog.Text_TLSE_dialog.Text = "La correction du checksum a échoué, veuillez signaler cet erreur"
                TLSE_dialog.ShowDialog()
            End If
        End Try
        Return
    End Sub

    Public Sub readmiidata()
        If Filever_text.Text = "US" Or Filever_text.Text = "EU" Or Filever_text.Text = "KR" Then
            Dim Reader As New PackageIO.Reader(savedataArc, PackageIO.Endian.Little)
            If Select_mii.SelectedItem = Select_mii.Items.Item(0) Then
                Reader.Position = &H1C70
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1CCE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(1) Then
                Reader.Position = &H22D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H232E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(2) Then
                Reader.Position = &H2930
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H298E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(3) Then
                Reader.Position = &H2F90
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2FEE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(4) Then
                Reader.Position = &H35F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H364E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(5) Then
                Reader.Position = &H3C50
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H3CAE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(6) Then
                Reader.Position = &H42B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H430E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(7) Then
                Reader.Position = &H4910
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H496E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(8) Then
                Reader.Position = &H4F70
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H4FCE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(9) Then
                Reader.Position = &H55D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H562E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(10) Then
                Reader.Position = &H5C30
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H5C8E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(11) Then
                Reader.Position = &H6290
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H62EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(12) Then
                Reader.Position = &H68F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H694E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(13) Then
                Reader.Position = &H6F50
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H6FAE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(14) Then
                Reader.Position = &H75B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H760E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(15) Then
                Reader.Position = &H7C10
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H7C6E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(16) Then
                Reader.Position = &H8270
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H82CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(17) Then
                Reader.Position = &H88D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H892E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(18) Then
                Reader.Position = &H8F30
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H8F8E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(19) Then
                Reader.Position = &H9590
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H95EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(20) Then
                Reader.Position = &H9BF0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H9C4E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(21) Then
                Reader.Position = &HA250
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HA2AE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(22) Then
                Reader.Position = &HA8B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HA90E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(23) Then
                Reader.Position = &HAF10
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HAF6E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(24) Then
                Reader.Position = &HB570
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HB5CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(25) Then
                Reader.Position = &HBBD0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HBC2E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(26) Then
                Reader.Position = &HC230
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HC28E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(27) Then
                Reader.Position = &HC890
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HC8EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(28) Then
                Reader.Position = &HCEF0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HCF4E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(29) Then
                Reader.Position = &HD550
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HD5AE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(30) Then
                Reader.Position = &HDBB0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HDC0E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(31) Then
                Reader.Position = &HE210
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HE26E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(32) Then
                Reader.Position = &HE870
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HE8CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(33) Then
                Reader.Position = &HEED0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HEF2E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(34) Then
                Reader.Position = &HF530
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HF58E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(35) Then
                Reader.Position = &HFB90
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HFBEE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(36) Then
                Reader.Position = &H101F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1024E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(37) Then
                Reader.Position = &H10850
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H108AE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(38) Then
                Reader.Position = &H10EB0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H10F0E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(39) Then
                Reader.Position = &H11510
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1156E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(40) Then
                Reader.Position = &H11B70
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H11BCE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(41) Then
                Reader.Position = &H121D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1222E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(42) Then
                Reader.Position = &H12830
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1288E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(43) Then
                Reader.Position = &H12E90
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H12EEE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(44) Then
                Reader.Position = &H134F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1354E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(45) Then
                Reader.Position = &H13B50
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H13BAE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(46) Then
                Reader.Position = &H141B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1420E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(47) Then
                Reader.Position = &H14810
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1486E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(48) Then
                Reader.Position = &H14E70
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H14ECE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(49) Then
                Reader.Position = &H154D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1552E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(50) Then
                Reader.Position = &H15B30
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H15B8E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(51) Then
                Reader.Position = &H16190
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H161EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(52) Then
                Reader.Position = &H167F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1684E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(53) Then
                Reader.Position = &H16E50
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H16EAE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(54) Then
                Reader.Position = &H174B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1750E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(55) Then
                Reader.Position = &H17B10
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H17B6E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(56) Then
                Reader.Position = &H18170
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H181CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(57) Then
                Reader.Position = &H187D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1882E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(58) Then
                Reader.Position = &H18E30
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H18E8E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(59) Then
                Reader.Position = &H19490
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H194EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(60) Then
                Reader.Position = &H19AF0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H19B4E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(61) Then
                Reader.Position = &H1A150
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1A1AE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(62) Then
                Reader.Position = &H1A7B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1A80E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(63) Then
                Reader.Position = &H1AE10
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1AE6E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(64) Then
                Reader.Position = &H1B470
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1B4CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(65) Then
                Reader.Position = &H1BAD0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1BB2E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(66) Then
                Reader.Position = &H1C130
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1C18E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(67) Then
                Reader.Position = &H1C790
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1C7EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(68) Then
                Reader.Position = &H1CDF0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1CE4E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(69) Then
                Reader.Position = &H1D450
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1D4AE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(70) Then
                Reader.Position = &H1DAB0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1DB0E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(71) Then
                Reader.Position = &H1E110
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1E16E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(72) Then
                Reader.Position = &H1E770
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1E7CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(73) Then
                Reader.Position = &H1EDD0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1EE2E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(74) Then
                Reader.Position = &H1F430
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1F48E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(75) Then
                Reader.Position = &H1FA90
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1FAEE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(76) Then
                Reader.Position = &H200F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2014E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(77) Then
                Reader.Position = &H20750
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H207AE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(78) Then
                Reader.Position = &H20DB0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H20E0E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(79) Then
                Reader.Position = &H21410
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2146E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(80) Then
                Reader.Position = &H21A70
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H21ACE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(81) Then
                Reader.Position = &H220D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2212E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(82) Then
                Reader.Position = &H22730
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2278E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(83) Then
                Reader.Position = &H22D90
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H22DEE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(84) Then
                Reader.Position = &H233F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2344E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(85) Then
                Reader.Position = &H23A50
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H23AAE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(86) Then
                Reader.Position = &H240B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2410E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(87) Then
                Reader.Position = &H24710
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2476E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(88) Then
                Reader.Position = &H24D70
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H24DCE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(89) Then
                Reader.Position = &H253D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2542E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(90) Then
                Reader.Position = &H25A30
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H25A8E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(91) Then
                Reader.Position = &H26090
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H260EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(92) Then
                Reader.Position = &H266F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2674E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(93) Then
                Reader.Position = &H26D50
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H26DAE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(94) Then
                Reader.Position = &H273B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2740E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(95) Then
                Reader.Position = &H27A10
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H27A6E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(96) Then
                Reader.Position = &H28070
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H280CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(97) Then
                Reader.Position = &H286D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2872E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(98) Then
                Reader.Position = &H28D30
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H28D8E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(99) Then
                Reader.Position = &H29390
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H293EE
            End If
        End If
        If Filever_text.Text = "JP" Then
            Dim Reader As New PackageIO.Reader(savedataArc, PackageIO.Endian.Little)
            If Select_mii.SelectedItem = Select_mii.Items.Item(0) Then
                Reader.Position = &H1C40
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1C9E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(1) Then
                Reader.Position = &H21D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H222E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(2) Then
                Reader.Position = &H2760
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H27BE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(3) Then
                Reader.Position = &H2CF0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2D4E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(4) Then
                Reader.Position = &H3280
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H32DE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(5) Then
                Reader.Position = &H3810
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H386E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(6) Then
                Reader.Position = &H3DA0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H3DFE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(7) Then
                Reader.Position = &H4330
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H438E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(8) Then
                Reader.Position = &H48C0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H491E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(9) Then
                Reader.Position = &H4E50
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H4EAE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(10) Then
                Reader.Position = &H53E0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H543E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(11) Then
                Reader.Position = &H5970
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H59CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(12) Then
                Reader.Position = &H5F00
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H5F5E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(13) Then
                Reader.Position = &H6490
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H64EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(14) Then
                Reader.Position = &H6A20
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H6A7E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(15) Then
                Reader.Position = &H6FB0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H700E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(16) Then
                Reader.Position = &H7540
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H759E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(17) Then
                Reader.Position = &H7AD0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H7B2E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(18) Then
                Reader.Position = &H8060
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H80BE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(19) Then
                Reader.Position = &H85F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H864E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(20) Then
                Reader.Position = &H8B80
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H8BDE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(21) Then
                Reader.Position = &H9110
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H916E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(22) Then
                Reader.Position = &H96A0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H96FE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(23) Then
                Reader.Position = &H9C30
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H9C8E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(24) Then
                Reader.Position = &HA1C0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HA21E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(25) Then
                Reader.Position = &HA750
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HA7AE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(26) Then
                Reader.Position = &HACE0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HAD3E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(27) Then
                Reader.Position = &HB270
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HB2CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(28) Then
                Reader.Position = &HB800
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HB85E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(29) Then
                Reader.Position = &HBD90
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HBDEE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(30) Then
                Reader.Position = &HC320
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HC37E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(31) Then
                Reader.Position = &HC8B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HC90E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(32) Then
                Reader.Position = &HCE40
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HCE9E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(33) Then
                Reader.Position = &HD3D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HD42E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(34) Then
                Reader.Position = &HD960
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HD9BE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(35) Then
                Reader.Position = &HDEF0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HDF4E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(36) Then
                Reader.Position = &HE480
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HE4DE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(37) Then
                Reader.Position = &HEA10
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HEA6E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(38) Then
                Reader.Position = &HEFA0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HEFFE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(39) Then
                Reader.Position = &HF530
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HF58E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(40) Then
                Reader.Position = &HFAC0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &HFB1E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(41) Then
                Reader.Position = &H10050
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H100AE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(42) Then
                Reader.Position = &H105E0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1063E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(43) Then
                Reader.Position = &H10B70
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H10BCE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(44) Then
                Reader.Position = &H11100
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1115E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(45) Then
                Reader.Position = &H11690
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H116EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(46) Then
                Reader.Position = &H11C20
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H11C7E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(47) Then
                Reader.Position = &H121B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1220E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(48) Then
                Reader.Position = &H12740
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1279E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(49) Then
                Reader.Position = &H12CD0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H12D2E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(50) Then
                Reader.Position = &H13260
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H132BE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(51) Then
                Reader.Position = &H137F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1384E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(52) Then
                Reader.Position = &H13D80
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H13DDE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(53) Then
                Reader.Position = &H14310
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1436E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(54) Then
                Reader.Position = &H148A0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H148FE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(55) Then
                Reader.Position = &H14E30
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H14E8E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(56) Then
                Reader.Position = &H153C0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1541E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(57) Then
                Reader.Position = &H15950
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H159AE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(58) Then
                Reader.Position = &H15EE0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H15F3E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(59) Then
                Reader.Position = &H16470
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H164CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(60) Then
                Reader.Position = &H16A00
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H16A5E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(61) Then
                Reader.Position = &H16F90
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H16FEE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(62) Then
                Reader.Position = &H17520
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1757E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(63) Then
                Reader.Position = &H17AB0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H17B0E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(64) Then
                Reader.Position = &H18040
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1809E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(65) Then
                Reader.Position = &H185D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1862E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(66) Then
                Reader.Position = &H18B60
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H18BBE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(67) Then
                Reader.Position = &H190F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1914E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(68) Then
                Reader.Position = &H19680
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H196DE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(69) Then
                Reader.Position = &H19C10
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H19C6E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(70) Then
                Reader.Position = &H1A1A0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1A1FE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(71) Then
                Reader.Position = &H1A730
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1A78E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(72) Then
                Reader.Position = &H1ACC0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1AD1E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(73) Then
                Reader.Position = &H1B250
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1B2AE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(74) Then
                Reader.Position = &H1B7E0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1B83E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(75) Then
                Reader.Position = &H1BD70
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1BDCE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(76) Then
                Reader.Position = &H1C300
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1C35E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(77) Then
                Reader.Position = &H1C890
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1C8EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(78) Then
                Reader.Position = &H1CE20
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1CE7E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(79) Then
                Reader.Position = &H1D3B0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1D40E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(80) Then
                Reader.Position = &H1D940
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1D99E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(81) Then
                Reader.Position = &H1DED0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1DF2E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(82) Then
                Reader.Position = &H1E460
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1E4BE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(83) Then
                Reader.Position = &H1E9F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1EA4E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(84) Then
                Reader.Position = &H1EF80
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1EFDE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(85) Then
                Reader.Position = &H1F510
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1F56E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(86) Then
                Reader.Position = &H1FAA0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H1FAFE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(87) Then
                Reader.Position = &H20030
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2008E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(88) Then
                Reader.Position = &H205C0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2061E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(89) Then
                Reader.Position = &H20B50
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H20BAE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(90) Then
                Reader.Position = &H210E0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2113E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(91) Then
                Reader.Position = &H21670
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H216CE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(92) Then
                Reader.Position = &H21C00
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H21C5E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(93) Then
                Reader.Position = &H22190
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H221EE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(94) Then
                Reader.Position = &H22720
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2277E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(95) Then
                Reader.Position = &H22CB0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H22D0E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(96) Then
                Reader.Position = &H23240
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2329E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(97) Then
                Reader.Position = &H237D0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2382E
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(98) Then
                Reader.Position = &H23D60
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H23DBE
            ElseIf Select_mii.SelectedItem = Select_mii.Items.Item(99) Then
                Reader.Position = &H242F0
                Text_Mii.Text = Reader.ReadHexString(&H5E)
                crcxmodem = &H2434E
            End If
        End If
    End Sub

    Public Sub Readmiiname()
        Try
            Dim Reader As New PackageIO.Reader(savedataArc, PackageIO.Endian.Little)
            If Filever_text.Text = "JP" Then
                Reader.Position = &H1C5A
                Select_mii.Items.Item(0) = "Mii 1 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H21EA
                Select_mii.Items.Item(1) = "Mii 2 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H277A
                Select_mii.Items.Item(2) = "Mii 3 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2D0A
                Select_mii.Items.Item(3) = "Mii 4 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H329A
                Select_mii.Items.Item(4) = "Mii 5 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H382A
                Select_mii.Items.Item(5) = "Mii 6 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H3DBA
                Select_mii.Items.Item(6) = "Mii 7 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H434A
                Select_mii.Items.Item(7) = "Mii 8 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H48DA
                Select_mii.Items.Item(8) = "Mii 9 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H4E6A
                Select_mii.Items.Item(9) = "Mii 10 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H53FA
                Select_mii.Items.Item(10) = "Mii 11 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H598A
                Select_mii.Items.Item(11) = "Mii 12 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H5F1A
                Select_mii.Items.Item(12) = "Mii 13 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H64AA
                Select_mii.Items.Item(13) = "Mii 14 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H6A3A
                Select_mii.Items.Item(14) = "Mii 15 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H6FCA
                Select_mii.Items.Item(15) = "Mii 16 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H755A
                Select_mii.Items.Item(16) = "Mii 17 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H7AEA
                Select_mii.Items.Item(17) = "Mii 18 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H807A
                Select_mii.Items.Item(18) = "Mii 19 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H860A
                Select_mii.Items.Item(19) = "Mii 20 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H8B9A
                Select_mii.Items.Item(20) = "Mii 21 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H912A
                Select_mii.Items.Item(21) = "Mii 22 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H96BA
                Select_mii.Items.Item(22) = "Mii 23 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H9C4A
                Select_mii.Items.Item(23) = "Mii 24 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HA1DA
                Select_mii.Items.Item(24) = "Mii 25 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HA76A
                Select_mii.Items.Item(25) = "Mii 26 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HACFA
                Select_mii.Items.Item(26) = "Mii 27 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HB28A
                Select_mii.Items.Item(27) = "Mii 28 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HB81A
                Select_mii.Items.Item(28) = "Mii 29 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HBDAA
                Select_mii.Items.Item(29) = "Mii 30 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HC33A
                Select_mii.Items.Item(30) = "Mii 31 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HC8CA
                Select_mii.Items.Item(31) = "Mii 32 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HCE5A
                Select_mii.Items.Item(32) = "Mii 33 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HD3EA
                Select_mii.Items.Item(33) = "Mii 34 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HD97A
                Select_mii.Items.Item(34) = "Mii 35 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HDF0A
                Select_mii.Items.Item(35) = "Mii 36 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HE49A
                Select_mii.Items.Item(36) = "Mii 37 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HEA2A
                Select_mii.Items.Item(37) = "Mii 38 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HEFBA
                Select_mii.Items.Item(38) = "Mii 39 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HF54A
                Select_mii.Items.Item(39) = "Mii 40 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HFADA
                Select_mii.Items.Item(40) = "Mii 41 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1006A
                Select_mii.Items.Item(41) = "Mii 42 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H105FA
                Select_mii.Items.Item(42) = "Mii 43 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H10B8A
                Select_mii.Items.Item(43) = "Mii 44 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1111A
                Select_mii.Items.Item(44) = "Mii 45 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H116AA
                Select_mii.Items.Item(45) = "Mii 46 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H11C3A
                Select_mii.Items.Item(46) = "Mii 47 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H121CA
                Select_mii.Items.Item(47) = "Mii 48 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1275A
                Select_mii.Items.Item(48) = "Mii 49 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H12CEA
                Select_mii.Items.Item(49) = "Mii 50 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1327A
                Select_mii.Items.Item(50) = "Mii 51 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1380A
                Select_mii.Items.Item(51) = "Mii 52 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H13D9A
                Select_mii.Items.Item(52) = "Mii 53 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1432A
                Select_mii.Items.Item(53) = "Mii 54 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H148BA
                Select_mii.Items.Item(54) = "Mii 55 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H14E4A
                Select_mii.Items.Item(55) = "Mii 56 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H153DA
                Select_mii.Items.Item(56) = "Mii 57 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1596A
                Select_mii.Items.Item(57) = "Mii 58 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H15EFA
                Select_mii.Items.Item(58) = "Mii 59 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1648A
                Select_mii.Items.Item(59) = "Mii 60 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H16A1A
                Select_mii.Items.Item(60) = "Mii 61 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H16FAA
                Select_mii.Items.Item(61) = "Mii 62 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1753A
                Select_mii.Items.Item(62) = "Mii 63 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H17ACA
                Select_mii.Items.Item(63) = "Mii 64 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1805A
                Select_mii.Items.Item(64) = "Mii 65 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H185EA
                Select_mii.Items.Item(65) = "Mii 66 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H18B7A
                Select_mii.Items.Item(66) = "Mii 67 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1910A
                Select_mii.Items.Item(67) = "Mii 68 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1969A
                Select_mii.Items.Item(68) = "Mii 69 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H19C2A
                Select_mii.Items.Item(69) = "Mii 70 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1A1BA
                Select_mii.Items.Item(70) = "Mii 71 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1A74A
                Select_mii.Items.Item(71) = "Mii 72 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1ACDA
                Select_mii.Items.Item(72) = "Mii 73 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1B26A
                Select_mii.Items.Item(73) = "Mii 74 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1B7FA
                Select_mii.Items.Item(74) = "Mii 75 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1BD8A
                Select_mii.Items.Item(75) = "Mii 76 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1C31A
                Select_mii.Items.Item(76) = "Mii 77 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1C8AA
                Select_mii.Items.Item(77) = "Mii 78 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1CE3A
                Select_mii.Items.Item(78) = "Mii 79 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1D3CA
                Select_mii.Items.Item(79) = "Mii 80 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1D95A
                Select_mii.Items.Item(80) = "Mii 81 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1DEEA
                Select_mii.Items.Item(81) = "Mii 82 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1E47A
                Select_mii.Items.Item(82) = "Mii 83 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1EA0A
                Select_mii.Items.Item(83) = "Mii 84 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1EF9A
                Select_mii.Items.Item(84) = "Mii 85 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1F52A
                Select_mii.Items.Item(85) = "Mii 86 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1FABA
                Select_mii.Items.Item(86) = "Mii 87 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2004A
                Select_mii.Items.Item(87) = "Mii 88 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H205DA
                Select_mii.Items.Item(88) = "Mii 89 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H20B6A
                Select_mii.Items.Item(89) = "Mii 90 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H210FA
                Select_mii.Items.Item(90) = "Mii 91 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2168A
                Select_mii.Items.Item(91) = "Mii 92 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H21C1A
                Select_mii.Items.Item(92) = "Mii 93 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H221AA
                Select_mii.Items.Item(93) = "Mii 94 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2273A
                Select_mii.Items.Item(94) = "Mii 95 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H22CCA
                Select_mii.Items.Item(95) = "Mii 96 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2325A
                Select_mii.Items.Item(96) = "Mii 97 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H237EA
                Select_mii.Items.Item(97) = "Mii 98 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H23D7A
                Select_mii.Items.Item(98) = "Mii 99 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2430A
                Select_mii.Items.Item(99) = "Mii 100 : " & Reader.ReadUnicodeString(10)
            Else
                Reader.Position = &H1C8A
                Select_mii.Items.Item(0) = "Mii 1 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H22EA
                Select_mii.Items.Item(1) = "Mii 2 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H294A
                Select_mii.Items.Item(2) = "Mii 3 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2FAA
                Select_mii.Items.Item(3) = "Mii 4 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H360A
                Select_mii.Items.Item(4) = "Mii 5 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H3C6A
                Select_mii.Items.Item(5) = "Mii 6 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H42CA
                Select_mii.Items.Item(6) = "Mii 7 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H492A
                Select_mii.Items.Item(7) = "Mii 8 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H4F8A
                Select_mii.Items.Item(8) = "Mii 9 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H55EA
                Select_mii.Items.Item(9) = "Mii 10 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H5C4A
                Select_mii.Items.Item(10) = "Mii 11 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H62AA
                Select_mii.Items.Item(11) = "Mii 12 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H690A
                Select_mii.Items.Item(12) = "Mii 13 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H6F6A
                Select_mii.Items.Item(13) = "Mii 14 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H75CA
                Select_mii.Items.Item(14) = "Mii 15 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H7C2A
                Select_mii.Items.Item(15) = "Mii 16 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H828A
                Select_mii.Items.Item(16) = "Mii 17 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H88EA
                Select_mii.Items.Item(17) = "Mii 18 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H8F4A
                Select_mii.Items.Item(18) = "Mii 19 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H95AA
                Select_mii.Items.Item(19) = "Mii 20 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H9C0A
                Select_mii.Items.Item(20) = "Mii 21 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HA26A
                Select_mii.Items.Item(21) = "Mii 22 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HA8CA
                Select_mii.Items.Item(22) = "Mii 23 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HAF2A
                Select_mii.Items.Item(23) = "Mii 24 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HB58A
                Select_mii.Items.Item(24) = "Mii 25 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HBBEA
                Select_mii.Items.Item(25) = "Mii 26 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HC24A
                Select_mii.Items.Item(26) = "Mii 27 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HC8AA
                Select_mii.Items.Item(27) = "Mii 28 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HCF0A
                Select_mii.Items.Item(28) = "Mii 29 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HD56A
                Select_mii.Items.Item(29) = "Mii 30 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HDBCA
                Select_mii.Items.Item(30) = "Mii 31 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HE22A
                Select_mii.Items.Item(31) = "Mii 32 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HE88A
                Select_mii.Items.Item(32) = "Mii 33 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HEEEA
                Select_mii.Items.Item(33) = "Mii 34 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HF54A
                Select_mii.Items.Item(34) = "Mii 35 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &HFBAA
                Select_mii.Items.Item(35) = "Mii 36 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1020A
                Select_mii.Items.Item(36) = "Mii 37 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1086A
                Select_mii.Items.Item(37) = "Mii 38 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H10ECA
                Select_mii.Items.Item(38) = "Mii 39 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1152A
                Select_mii.Items.Item(39) = "Mii 40 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H11B8A
                Select_mii.Items.Item(40) = "Mii 41 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H121EA
                Select_mii.Items.Item(41) = "Mii 42 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1284A
                Select_mii.Items.Item(42) = "Mii 43 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H12EAA
                Select_mii.Items.Item(43) = "Mii 44 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1350A
                Select_mii.Items.Item(44) = "Mii 45 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H13B6A
                Select_mii.Items.Item(45) = "Mii 46 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H141CA
                Select_mii.Items.Item(46) = "Mii 47 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1482A
                Select_mii.Items.Item(47) = "Mii 48 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H14E8A
                Select_mii.Items.Item(48) = "Mii 49 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H154EA
                Select_mii.Items.Item(49) = "Mii 50 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H15B4A
                Select_mii.Items.Item(50) = "Mii 51 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H161AA
                Select_mii.Items.Item(51) = "Mii 52 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1680A
                Select_mii.Items.Item(52) = "Mii 53 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H16E6A
                Select_mii.Items.Item(53) = "Mii 54 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H174CA
                Select_mii.Items.Item(54) = "Mii 55 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H17B2A
                Select_mii.Items.Item(55) = "Mii 56 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1818A
                Select_mii.Items.Item(56) = "Mii 57 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H187EA
                Select_mii.Items.Item(57) = "Mii 58 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H18E4A
                Select_mii.Items.Item(58) = "Mii 59 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H194AA
                Select_mii.Items.Item(59) = "Mii 60 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H19B0A
                Select_mii.Items.Item(60) = "Mii 61 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1A16A
                Select_mii.Items.Item(61) = "Mii 62 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1A7CA
                Select_mii.Items.Item(62) = "Mii 63 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1AE2A
                Select_mii.Items.Item(63) = "Mii 64 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1B48A
                Select_mii.Items.Item(64) = "Mii 65 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1BAEA
                Select_mii.Items.Item(65) = "Mii 66 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1C14A
                Select_mii.Items.Item(66) = "Mii 67 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1C7AA
                Select_mii.Items.Item(67) = "Mii 68 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1CE0A
                Select_mii.Items.Item(68) = "Mii 69 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1D46A
                Select_mii.Items.Item(69) = "Mii 70 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1DACA
                Select_mii.Items.Item(70) = "Mii 71 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1E12A
                Select_mii.Items.Item(71) = "Mii 72 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1E78A
                Select_mii.Items.Item(72) = "Mii 73 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1EDEA
                Select_mii.Items.Item(73) = "Mii 74 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1F44A
                Select_mii.Items.Item(74) = "Mii 75 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H1FAAA
                Select_mii.Items.Item(75) = "Mii 76 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2010A
                Select_mii.Items.Item(76) = "Mii 77 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2076A
                Select_mii.Items.Item(77) = "Mii 78 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H20DCA
                Select_mii.Items.Item(78) = "Mii 79 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2142A
                Select_mii.Items.Item(79) = "Mii 80 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H21A8A
                Select_mii.Items.Item(80) = "Mii 81 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H220EA
                Select_mii.Items.Item(81) = "Mii 82 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2274A
                Select_mii.Items.Item(82) = "Mii 83 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H22DAA
                Select_mii.Items.Item(83) = "Mii 84 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2340A
                Select_mii.Items.Item(84) = "Mii 85 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H23A6A
                Select_mii.Items.Item(85) = "Mii 86 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H240CA
                Select_mii.Items.Item(86) = "Mii 87 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2472A
                Select_mii.Items.Item(87) = "Mii 88 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H24D8A
                Select_mii.Items.Item(88) = "Mii 89 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H253EA
                Select_mii.Items.Item(89) = "Mii 90 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H25A4A
                Select_mii.Items.Item(90) = "Mii 91 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H260AA
                Select_mii.Items.Item(91) = "Mii 92 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2670A
                Select_mii.Items.Item(92) = "Mii 93 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H26D6A
                Select_mii.Items.Item(93) = "Mii 94 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H273CA
                Select_mii.Items.Item(94) = "Mii 95 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H27A2A
                Select_mii.Items.Item(95) = "Mii 96 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H2808A
                Select_mii.Items.Item(96) = "Mii 97 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H286EA
                Select_mii.Items.Item(97) = "Mii 98 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H28D4A
                Select_mii.Items.Item(98) = "Mii 99 : " & Reader.ReadUnicodeString(10)
                Reader.Position = &H293AA
                Select_mii.Items.Item(99) = "Mii 100 : " & Reader.ReadUnicodeString(10)
            End If
            Select_mii.SelectedItem = TLSE_miiprofile.Select_mii.SelectedItem
        Catch ex As Exception
            If Select_language.SelectedItem = Select_language.Items.Item(0) Then
                TLSE_dialog.Text_TLSE_dialog.Text = "Failed to read Mii names"
                TLSE_dialog.ShowDialog()
            End If
            If Select_language.SelectedItem = Select_language.Items.Item(1) Then
                TLSE_dialog.Text_TLSE_dialog.Text = "La lecture des noms des Mii a échoué"
                TLSE_dialog.ShowDialog()
            End If
        End Try
    End Sub

End Class